apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test QA
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  run-unit-test:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Run scan
        with:
          orgname: cloudbees-compliance-partner-development
          token: 5187082e-6732-489e-8bcd-c7e8a7341d81
        uses: cloudbees-io/snyk-sast-scan-code@v1
        id: run-bundled-sonar-scan
