apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sonar-bundled-so
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  run-unit-test:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      # - name: Run scan
      #   kind: scan
      #   uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
      #   with:
      #     language: LANGUAGE_PHP
